project_id = "edznwgvyqpsibnkqqeby"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://348933516.github.io/preview/"
additional_redirect_urls = ["http://127.0.0.1:5173", "https://348933516.github.io/preview/", "https://maplestorynk.online/preview/"]
enable_signup = false
